basePath: /api/v1
definitions:
  dto.LoginDetails:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  dto.RegisterDetails:
    properties:
      email:
        type: string
      password:
        maxLength: 20
        minLength: 8
        type: string
      username:
        maxLength: 20
        minLength: 4
        type: string
    required:
    - email
    - password
    - username
    type: object
host: localhost:8080
info:
  contact: {}
  description: Service for buying/selling collectable cards
  title: Card store api
  version: "1.0"
paths:
  /auth/login:
    post:
      description: Checks the user data and returns a jwt token on correct Login
      parameters:
      - description: Login details
        in: body
        name: details
        required: true
        schema:
          $ref: '#/definitions/dto.LoginDetails'
      responses:
        "200":
          description: OK
      summary: Logs in the user
      tags:
      - Auth
  /auth/register:
    post:
      description: Checks the user data and adds it to the repo
      parameters:
      - description: Register details
        in: body
        name: details
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterDetails'
      responses:
        "201":
          description: Created
      summary: Registers the user
      tags:
      - Auth
swagger: "2.0"
