basePath: /api/v1
definitions:
  dto.CreateCard:
    properties:
      imageUrl:
        type: string
      name:
        type: string
      price:
        type: number
      text:
        type: string
    required:
    - name
    - price
    - text
    type: object
  dto.GetCard:
    properties:
      id:
        type: integer
      imageUrl:
        type: string
      name:
        type: string
      price:
        type: number
      text:
        type: string
    type: object
  dto.LoginDetails:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  dto.RegisterDetails:
    properties:
      email:
        type: string
      password:
        maxLength: 20
        minLength: 8
        type: string
      username:
        maxLength: 20
        minLength: 4
        type: string
    required:
    - email
    - password
    - username
    type: object
host: localhost:8080
info:
  contact: {}
  description: Service for buying/selling collectable cards
  title: Card store api
  version: "1.0"
paths:
  /auth/login:
    post:
      description: Checks the user data and returns a jwt token on correct Login
      parameters:
      - description: Login details
        in: body
        name: details
        required: true
        schema:
          $ref: '#/definitions/dto.LoginDetails'
      responses:
        "200":
          description: OK
      summary: Logs in the user
      tags:
      - Auth
  /auth/register:
    post:
      description: Checks the user data and adds it to the repo
      parameters:
      - description: Register details
        in: body
        name: details
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterDetails'
      responses:
        "201":
          description: Created
      summary: Registers the user
      tags:
      - Auth
  /card:
    get:
      description: Fetches all existing cards
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GetCard'
      summary: Fetch all cards
      tags:
      - Card
    post:
      description: Creates a new card
      parameters:
      - description: Authenticator
        in: header
        name: Authorization
        required: true
        type: string
      - description: new card data
        in: body
        name: card
        required: true
        schema:
          $ref: '#/definitions/dto.CreateCard'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.GetCard'
      summary: Create new card
      tags:
      - Card
swagger: "2.0"
