version: '3.1'

services:
  # api:
  #   container_name: card-store
  #   build: ./api
  #   ports:
  #     - 9090:8080
  #   links:
  #     - mongo
  #   depends_on:
  #     - mongo
  #   environment:
  #     PORT: 8080
  #     AUTH_SECRET_KEY: /run/secrets/auth_key
  #     DB_CONNECTION_URI: mongodb://db:27017
  #     DB_NAME: store
  #     DB_TASK_COLLECTION_NAME: tasks
  #     DB_USER_COLLECTION_NAME: users
  db:
    container_name: store-db
    image: postgres:latest
    restart: always
    environment:
      - 'POSTGRES_DB=store'
      - 'POSTGRES_USER=user'
      - 'POSTGRES_PASSWORD=password'
      - 'PGDATA=/data/postgres'
    ports:
      - '5444:5432'
    volumes:
      - store-db-data:/data/postgres
  cache:
    container_name: store-cache
    hostname: valkey
    image: valkey/valkey:7.2.5
    volumes:
      - ./config/valkey.conf:/etc/valkey/valkey.conf
      # - store-cache-data:/data
    command: valkey-server /etc/valkey/valkey.conf
    ports:
      - 6380:6379

volumes:
  store-db-data:
  # store-cache-data:

# secrets:
#   auth_key:
#     file: ./auth_key.txt
